#+LANGUAGE: fr

#+begin_src emacs-lisp :exports none
  (defalias 'km-watch-main-pdf
   (kmacro "C-x p f m a i n <return> C-c C-w C-c C-p C-x b <return>")) 
#+end_src
 
#+begin_export typst-ts
#show link: body => {
   text(weight: 900, body)
}
#+end_export
-----
/Influence de la structure cellulaire et moléculaire de l'appareil tégumentaire dans les processus de protection et de maintien de la peau./

* TODO Histologie

La peau se compose de trois couches majeures dont l'épiderme est la plus externe. En dessous, on retrouve le derme, recouvrant l'hypoderme[fn:3]. Chacune est composée de différentes strates: l'épiderme est composé — en partant du derme vers l'extérieur — du stratum basale, du stratum spinosum, du stratum granulosum, du stratum lucidum, et enfin du stratum corneum. La composition en cellules de chaque strate diffère en fonction de nombreux paramètres dont la position et l'âge du sujet.[cite:@marie-danielleImprovingHumanSkin2014]
Il existe différents types de cellules: les kératinocytes sont les plus nombreux dans l'épiderme, mais on peut aussi y voir des cellules de Langerhans, et des cellules de Merkel en plus petit nombre. [cite:@agarwalHistologySkin2024]

L'épiderme est en renouvellement permanent. Les kératinocytes se différencient en partant de la couche basale, et maturent en se déplaçant vers l'extérieur. On retrouve dans le stratum corneum des kératinocytes anucléés, inactifs, et très kératinisés. Les couches squameuse et basale forment /a contrario/ la *couche nucléée* de l'épiderme.
On estime la durée physiologique du renouvellement de la peau à 40 jours environ [cite:@kosterMakingEpidermis2009].


Le derme a une épaisseur variable[fn:4] et possède la structure nécessaire à l'innervation et l'irrigation de l'épiderme[cite:@SkinAnatomyOverview2019]. Il projette des digitations (/dermal papillae/ [cite:@morganDermalPapillaInstructive2014]) en direction de ce dernier; ces projections contiennent des progéniteurs du follicule pileux, et determinent la fréquence de regenération et la qualité du poil.


La jonction dermo-épidermique est l'interface entre la couche basale de l'épiderme et la couche supérieure du derme.


[fn:1] Bactéries, UV[cite:@brennerProtectiveRoleMelanin2008], irritants 

[fn:2] Contrairement à l'épiderme

[fn:3] L'hypoderme n'est pas considéré comme faisant partie de la peau. 

[fn:4] Jusqu'à 4mm[cite:@HttpsWwwuoanbareduiqEStoreImages] 
